on: push
jobs:
   job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          uses: docker://amazoncorretto:8
          with:
            entrypoint: ./gradlew assemble

        - name: Test
          uses: docker://amazoncorretto:8
          with:
            entrypoint: ./gradlew test
